SpecCoreOSDev/Core/src/SpecSheetsCore/Models/AdminViewModels/LocationTypeViewModel.cs
using Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SpecSheetsCore.Models.AdminViewModels
{
    public class LocationTypeViewModel
    {
        public List<LocationType> locationTemplates { get; set; }

        public LocationType locationType { get; set; }
    }
}

SpecCoreOSDev/Core/src/SpecSheetsCore/Controllers/Admin/LocationTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SpecSheetsCore.Models.AdminViewModels;
using Repository;
using Models;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SpecSheetsCore.Controllers.Admin
{
    [Authorize]
    [Area("Admin")]
    public class LocationTypeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            LocationTypeViewModel model = new LocationTypeViewModel();
            model.locationTemplates = new LocationTypeRepository().GetLocationTypes();

            return View(model);
        }

        [HttpPost]
        public IActionResult Add(LocationTypeViewModel model)
        {
            new LocationTypeRepository().SaveLocation(model.locationType);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            new LocationTypeRepository().DeleteLocationType(id);
            return RedirectToAction("Index");
        }
    }
}

SpecCoreOSDev/Core/src/SpecSheetsCore/Areas/Admin/Views/LocationType/Index.cshtml
@model SpecSheetsCore.Models.AdminViewModels.LocationTypeViewModel

<div id="page-wrapper" class="gray-bg">
    <div class="row border-bottom">
        <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li>
                    <span class="m-r-sm text-muted welcome-message">Welcome to INSPINIA+ Admin Theme.</span>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope"></i>  <span class="label label-warning">16</span>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <div class="dropdown-messages-box">
                                <a href="profile.html" class="pull-left">
                                    <img alt="image" class="img-circle" src="~/images/a7.jpg">
                                </a>
                                <div class="media-body">
                                    <small class="pull-right">46h ago</small>
                                    <strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a href="profile.html" class="pull-left">
                                    <img alt="image" class="img-circle" src="~/images/a4.jpg">
                                </a>
                                <div class="media-body ">
                                    <small class="pull-right text-navy">5h ago</small>
                                    <strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>
                                    <small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="dropdown-messages-box">
                                <a href="profile.html" class="pull-left">
                                    <img alt="image" class="img-circle" src="~/images/profile.jpg">
                                </a>
                                <div class="media-body ">
                                    <small class="pull-right">23h ago</small>
                                    <strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>
                                    <small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="mailbox.html">
                                    <i class="fa fa-envelope"></i> <strong>Read All Messages</strong>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell"></i>  <span class="label label-primary">8</span>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="mailbox.html">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> You have 16 messages
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="profile.html">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="grid_options.html">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="notifications.html">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>


                <li>
                    <a href="login.html">
                        <i class="fa fa-sign-out"></i> Log out
                    </a>
                </li>
            </ul>

        </nav>
    </div>
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Location List</h2>
            <ol class="breadcrumb">
                <li>
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    <a>Location Type</a>
                </li>
                <li class="active">
                    <strong>Location Type list</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2" style="padding-top:40px;">
            <button type="button" class="btn btn-primary actAddLocationType">
                Add Location Type
            </button>

            <div class="modal inmodal" id="LocationModel" tabindex="-1" role="dialog" aria-hidden="true" data-LocationTypeId="0">
                <div class="modal-dialog">
                    <div class="modal-content animated bounceInRight">
                        @using (Html.BeginForm("Add", "LocationType", new { @class = "form-horizontal", role = "form" }))
                        {
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                <h4 class="modal-title"><span class="modalTitle">Add</span> Location Type</h4>
                            </div>
                            <div class="modal-body">
                                <div class="form-group">
                                    <label>Location Type:</label>
                                    @Html.HiddenFor(x => x.locationType.LocationTypeId)
                                    @Html.TextBoxFor(x => x.locationType.Name, new { @class = "form-control", placeholder = "Location Type Name" })
                                </div>
                                <div class="form-group">
                                    <label>Category:</label>
                                    @Html.TextBoxFor(x => x.locationType.Category, new { @class = "form-control", placeholder = "Category Name" })
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight ecommerce">

        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-content">
                        <table id="tbllocation" class="tbllocation footable table table-stripped toggle-arrow-tiny" data-page-size="15">
                            <thead>
                                <tr>
                                    <th data-toggle="true">Location Type</th>
                                    <th data-hide="phone,tablet">Category</th>
                                    <th class="text-right" data-sort-ignore="true">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var type in Model.locationTemplates)
                                {
                                    <tr>
                                        <td>
                                            @type.Name
                                        </td>
                                        <td>
                                            @type.Category
                                        </td>
                                        <td class="text-right">
                                            <div class="btn-group">
                                                <button class="btn-white btn btn-xs actEdit" data-LocationTypeId="@type.LocationTypeId" data-Category="@type.Category" data-LocationTypeName="@type.Name">Edit</button>
                                                @*<a asp-area="Admin" asp-controller="LocationType" asp-action="Delete" asp-route-Id="@type.LocationTypeId" class="btn-white btn btn-xs">Delete</a>*@
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="3">
                                        <ul class="pagination pull-right"></ul>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="pull-right">
            10GB of <strong>250GB</strong> Free.
        </div>
        <div>
            <strong>Copyright</strong> Source Systems &copy; 2015-2020
        </div>
    </div>
</div>

@section Scripts{

    <script type="text/javascript">

        var $table = null;
        $(document).ready(function () {

            var $table = $("#tbllocation");

            InitializeTable($table);

            $(".actAddLocationType").on('click', function () {

                $(".modalTitle").text("Add");
                $("#locationType_LocationTypeId").val("0");
                $("#locationType_Name").val("");
                $("#locationType_Category").val("");

                $("#LocationModel").modal();

            });

            $(".actEdit").on('click', function () {

                var button = $(this);
                var LocationTypeId = button.attr("data-LocationTypeId");
                var LocationTypeName = button.attr("data-LocationTypeName");
                var Category = button.attr("data-Category");

                $(".modalTitle").text("Update");

                $("#locationType_LocationTypeId").val(LocationTypeId);
                $("#locationType_Name").val(LocationTypeName);
                $("#locationType_Category").val(Category);


                $("#LocationModel").modal();

            });
        });

        function InitializeTable($table) {

            /* Init DataTables */
            var oTable = $table.DataTable();
        }
    </script>
}