SpecCoreOSDev/Core/src/SpecSheetsCore/Controllers/Admin/AssociationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SpecSheetsCore.Models.AdminViewModels;
using Repository;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SpecSheetsCore.Controllers.Admin
{
    [Authorize]
    [Area("Admin")]
    public class AssociationController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            AssociationViewModel model = new AssociationViewModel();
            model.associations = new LocationTypeRepository().GetAssociation();
            
            return View(model);
        }

        public IActionResult Add()
        {
            AssociationViewModel model = new AssociationViewModel();
            model.association = new LocationTradeMaterialAssociation();

			var locationList = new LocationTypeRepository().GetLocationTypes().OrderBy(x => x.Name);
			var tradeList = new TradeRepository().GetTrades().OrderBy(x => x.Name);
			var materialList = new MaterialRepository().GetMaterials().OrderBy(x => x.Name);

			model.locations = new SelectList(locationList, "LocationTypeId", "Name");
            model.trades = new SelectList(tradeList, "TradeId", "Name");
            model.materials = new SelectList(materialList, "MaterialId", "Name");

            return View(model);
        }

        [HttpPost]
        public IActionResult Save(AssociationViewModel model)
        {
            new LocationTypeRepository().SaveAssociation(model.association);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            new LocationTypeRepository().DeleteAssociation(id);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            AssociationViewModel model = new AssociationViewModel();
            model.editAssociation = new LocationTypeRepository().GetAssociation(id);

            return View(model);
        }

        [HttpPost]
        public IActionResult Update(AssociationViewModel model)
        {
            var association = model.editAssociation;
            new LocationTypeRepository().UpdateAssociation(association.AssociationId, association.DefaultQuantity);

            return RedirectToAction("Index");
        }
    }
}

SpecCoreOSDev/Core/src/SpecSheetsCore/Controllers/Admin/MaterialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SpecSheetsCore.Models.AdminViewModels;
using Repository;
using Models;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SpecSheetsCore.Controllers.Admin
{
    [Authorize]
    [Area("Admin")]
    public class MaterialController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            MaterialViewModel model = new MaterialViewModel();
            model.materials = new MaterialRepository().GetMaterials();

            return View(model);
        }

        //public IActionResult Add()
        //{
        //    MaterialViewModel model = new MaterialViewModel();
        //    model.material = new Material();

        //    return View(model);
        //}

        [HttpPost]
        public IActionResult Add(MaterialViewModel model)
        {
            new MaterialRepository().SaveMaterial(model.material);
            return RedirectToAction("Index");
        }


        //public IActionResult Edit(int Id)
        //{
        //    MaterialViewModel model = new MaterialViewModel();
        //    model.material = new MaterialRepository().GetMaterial(Id);

        //    return View("Add", model);
        //}
    }
}

SpecCoreOSDev/Core/src/SpecSheetsCore/Controllers/Admin/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SpecSheetsCore.Models.AdminViewModels;
using Repository;
using Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SpecSheetsCore.Controllers.Admin
{
    [Authorize]
    [Area("Admin")]
    public class TagController : Controller
    {
        public IActionResult Index()
        {
            TagViewModel model = new TagViewModel();
            model.tags = new TagRepository().GetTags();
            return View(model);
        }
        [HttpPost]
        public IActionResult Add(TagViewModel model)
        {
            new TagRepository().SaveTag(model.tag);
            return RedirectToAction("Index");
        }
        
        public IActionResult Delete(int id)
        {
            new TagRepository().DeleteTag(id);
            return RedirectToAction("Index");
        }
        //public IActionResult Edit(int id)
        //{
        //    TagViewModel model = new TagViewModel();
        //    model.editTags = new TagRepository().GetTags(id);

        //    return View(model);
        //}
    }
}

SpecCoreOSDev/Core/src/SpecSheetsCore/Controllers/Admin/TradeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SpecSheetsCore.Models.AdminViewModels;
using Repository;
using Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SpecSheetsCore.Controllers.Admin
{
    [Authorize]
    [Area("Admin")]
    public class TradeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            TradeViewModel model = new TradeViewModel();
            model.trades = new TradeRepository().GetTrades();

            return View(model);
        }

        //public IActionResult Add()
        //{
        //    TradeViewModel model = new TradeViewModel();
        //    model.trade = new Trade();

        //    return View(model);
        //}

        [HttpPost]
        public IActionResult Add(TradeViewModel model)
        {
            new TradeRepository().SaveTrade(model.trade);
            return RedirectToAction("Index");
        }


        //public IActionResult Edit(int Id)
        //{
        //    TradeViewModel model = new TradeViewModel();
        //    model.trade = new TradeRepository().GetTrade(Id);

        //    return View("Add", model);
        //}

        public IActionResult Delete(int id)
        {
            new LocationTypeRepository().DeleteLocationType(id);
            return RedirectToAction("Index");
        }
    }
}

SpecCoreOSDev/Core/src/SpecSheetsCore/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>@ViewData["Title"]</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/admin/bootstrap/dist/css/bootstrap.css" />

    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/admin/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />


    </environment>
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />

    <!-- Toastr style -->
    <link href="~/css/admin/plugins/toastr/toastr.min.css" rel="stylesheet">

    <!-- Gritter -->
    <link href="~/js/admin/plugins/gritter/jquery.gritter.css" rel="stylesheet">

    <link href="~/css/admin/plugins/dataTables/datatables.min.css" rel="stylesheet">
    <link href="~/css/admin/animate.css" rel="stylesheet">
    <link href="~/css/admin/style.css" rel="stylesheet">

</head>

<body>
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <span>
                                <img alt="image" class="img-circle" src="~/images/profile_small.jpg" />
                            </span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="block m-t-xs">
                                        <strong class="font-bold">Administrator</strong>
                                    </span>
                                </span>
                            </a>

                        </div>
                        <div class="logo-element">
                            IN+
                        </div>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="LocationType" asp-action="Index"><i class="fa fa-th-large"></i> <span class="nav-label">Location Type</span></a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Trade" asp-action="Index"><i class="fa fa-th-large"></i> <span class="nav-label">Trade</span></a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Material" asp-action="Index"><i class="fa fa-th-large"></i> <span class="nav-label">Material</span></a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Association" asp-action="Index"><i class="fa fa-th-large"></i> <span class="nav-label">Association</span></a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Tag" asp-action="Index"><i class="fa fa-th-large"></i> <span class="nav-label">Tag</span></a>
                    </li>

                </ul>

            </div>
        </nav>


        @RenderBody()






    </div>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/admin/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/admin/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/admin/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>

        <script src="~/js/admin/site.min.js" asp-append-version="true"></script>
    </environment>

    <!-- Mainly scripts -->
    <script src="~/js/admin/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/js/admin/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Flot -->
    <script src="~/js/admin/plugins/flot/jquery.flot.js"></script>
    <script src="~/js/admin/plugins/flot/jquery.flot.tooltip.min.js"></script>
    <script src="~/js/admin/plugins/flot/jquery.flot.spline.js"></script>
    <script src="~/js/admin/plugins/flot/jquery.flot.resize.js"></script>
    <script src="~/js/admin/plugins/flot/jquery.flot.pie.js"></script>

    <!-- Peity -->
    <script src="~/js/admin/plugins/peity/jquery.peity.min.js"></script>
    <script src="~/js/admin/demo/peity-demo.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="~/js/admin/inspinia.js"></script>
    <script src="~/js/admin/plugins/pace/pace.min.js"></script>

    <!-- jQuery UI -->
    <script src="~/js/admin/plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- GITTER -->
    <script src="~/js/admin/plugins/gritter/jquery.gritter.min.js"></script>

    <!-- Sparkline -->
    <script src="~/js/admin/plugins/sparkline/jquery.sparkline.min.js"></script>

    <!-- Sparkline demo data  -->
    <script src="~/js/admin/demo/sparkline-demo.js"></script>

    <!-- ChartJS-->
    <script src="~/js/admin/plugins/chartJs/Chart.min.js"></script>

    <!-- Toastr -->
    <script src="~/js/admin/plugins/toastr/toastr.min.js"></script>

    <script src="~/js/admin/plugins/dataTables/datatables.min.js"></script>

    <script>
        $(document).ready(function () {
            setTimeout(function () {
                toastr.options = {
                    closeButton: true,
                    progressBar: true,
                    showMethod: 'slideDown',
                    timeOut: 4000
                };
                toastr.success('Adminstration', 'Welcome to SpecSheets');

            }, 1300);

        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>