SpecCoreOSDev/Core/src/SpecSheetsCore/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Models;
using Repository;
using SpecSheetsCore.Models;
using SpecSheetsCore.Models.AdminViewModels;
using SpecSheetsCore.Models.LoggedInViewModels;
using SpecSheetsCore.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using System.Web;
using Microsoft.Office.Interop.Word;
using System.Text.RegularExpressions;


// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SpecSheetsCore.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailSender _emailSender;
        private readonly ISmsSender _smsSender;
        private readonly ILogger _logger;
		private readonly IHostingEnvironment _hostingEnvironment;

		public ProjectsController(
        UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager,
        IEmailSender emailSender,
        ISmsSender smsSender,
        ILoggerFactory loggerFactory,
		IHostingEnvironment hostingEnvironment)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _smsSender = smsSender;
            _logger = loggerFactory.CreateLogger<ProjectsController>();
			_hostingEnvironment = hostingEnvironment;
		}

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            // Generate the token and send it
            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                return View("Error");
            }

            ProjectsViewModel model = new ProjectsViewModel();

            model.IsInvitedUser = new InviteUserRepository().CheckIsUserInvited(user.Id);
            model.projects = new ProjectRepository().GetProjects(user.Id);
            model.projects.ForEach(x => x.IsOwner = (x.AspNetUsersId == user.Id));

            return View(model);
        }

        //Nabeel
        //[Authorize(Roles = "Retail")]
        public async Task<IActionResult> Add()
        {
            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                return View("Error");
            }

            ProjectViewModel model = new ProjectViewModel();
            model.project = new ProjectDetails();

            return View("AddProject", model);
        }

        //Nabeel
        [HttpPost]
        //[Authorize(Roles = "Retail")]
        public async Task<IActionResult> Add(ProjectViewModel model)
        {
            // Generate the token and send it
            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                return View("Error");
            }

            model.project.AspNetUsersId = user.Id;

            new ProjectRepository().SaveProject(model.project);

            if (model.project.ProjectId > 0)
            {
                return RedirectToAction("Details", new { Id = model.project.ProjectId });
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Details(int Id)
        {
            var user = await GetCurrentUserAsync();
            if (user == null)
            {
                return View("Error");
            }

            ProjectViewModel model = new ProjectViewModel();
            model.project = new ProjectRepository().GetProjectDetailsWithPermissions(Id, user.Id);

            model.project.IsOwner = (model.project.AspNetUsersId == user.Id);

            var locationTrades = new LocationRepository().GetTradesByProjectId(Id);
            model.locationTrades = locationTrades;

            locationTrades.Insert(0, new LocationTrade() { TradeId = 0, TradeName = "ALL" });
            ViewBag.Trades = new SelectList(locationTrades, "TradeId", "TradeName");

            return View("ProjectDetails", model);
        }

        public IActionResult AddProjectLocationTrade(LocationViewModel model) // Location Id
        {
            // Trade, LocationTypeId, ProjectLocationId
            int ProjectLocationTradeId = new ProjectRepository().SaveProjectTrade(model.trade, model.location.LocationId);

            var projectlocationTrade = new
            {
                LocationId = model.location.LocationId,
                LocationName = model.location.LocationName,
                ProjectLocationTradeId = ProjectLocationTradeId,
                ProjectLocationTradeName = model.trade.Name
            };

            return base.Json(new { Message = true, result = projectlocationTrade });
        }

		[HttpPost]
        public async Task<IActionResult> UpdateMultipleImagesNotesTags()
        {
            var files = Request.Form.Files;
            var projectId = Request.Form["projectId"][0];
            var locationId = Request.Form["locationId"][0];
            var tradeId = Request.Form["tradeId"][0];
            var materialId = Request.Form["materialId"][0];
            var arrSelectedImgIds = Request.Form["arrSelectedImgIds"][0];
            var notesText = Request.Form["notesText"][0];
            string[] ids = arrSelectedImgIds.Split(',');

            List<ProjectTradeMaterialImage> lstMultipleSelectedImages = new List<ProjectTradeMaterialImage>();

            foreach (var item in ids)
            {
                ProjectTradeMaterialImage model = new ProjectTradeMaterialImage();
                model.Id = int.Parse(item);
                lstMultipleSelectedImages.Add(model);
            }
            var user1 = await GetCurrentUserAsync();
            var Sequence = GetImagesOrderSequence(int.Parse(projectId), int.Parse(tradeId), int.Parse(materialId), user1.Id);
            NoteHistory modelNote = new NoteHistory();

            ProjectTags pTag = new ProjectTags();

            foreach (var multipleSelectedImages in lstMultipleSelectedImages)
            {
                using (var stream = new MemoryStream())
                {
                    var user = await GetCurrentUserAsync();
                    multipleSelectedImages.Id = multipleSelectedImages.Id;
                    multipleSelectedImages.ProjectId = int.Parse(projectId);
                    multipleSelectedImages.LocationId = int.Parse(locationId);
                    multipleSelectedImages.TradeId = int.Parse(tradeId);
                    multipleSelectedImages.MaterialId = int.Parse(materialId);
                    multipleSelectedImages.AspNetUsersId = user.Id;
                    if (Sequence != null)
                    {
                        foreach (var ord in Sequence.ToList())
                        {
                            multipleSelectedImages.ImageOrderSequence = Convert.ToInt32(ord.ImageOrderSequence) + 1;
                        }
                    }
                    new ProjectRepository().UpdateMultipleSelectedImgTags(multipleSelectedImages.Id, multipleSelectedImages.ProjectId, multipleSelectedImages.LocationId, multipleSelectedImages.TradeId, multipleSelectedImages.MaterialId, multipleSelectedImages.AspNetUsersId, multipleSelectedImages.ImageOrderSequence);

                    //Inserting notes
                    modelNote.Notes = notesText;
                    modelNote.DateTimeStamp = DateTime.Now;
                    modelNote.AspNetUsersId = user.Id;
                    new ProjectRepository().SaveNoteHistory(Convert.ToInt32(multipleSelectedImages.Id), modelNote.Notes, modelNote.DateTimeStamp, modelNote.AspNetUsersId);


                    //save tags KS 13/12/2018
                    pTag.LocationId = int.Parse(locationId);
                    pTag.TradeId = int.Parse(tradeId);
                    pTag.MaterialId = int.Parse(materialId);
                    pTag.ProjectLocationTradeMaterialImageId = Convert.ToInt32(multipleSelectedImages.Id);
                    pTag.ProjectId = int.Parse(projectId);
                    pTag.AspNetUsersId = user.Id;
                    new ProjectRepository().SaveProjectTags(pTag);
                }
            }
            LocationViewModel locationViewModel = new LocationViewModel();
            List<ProjectTradeMaterialImage> lstImages = new List<ProjectTradeMaterialImage>();
            var userId = await GetCurrentUserAsync();
            var userLogged = userId.Id;
            var data = new ProjectRepository().GetProjectMultipleImagesWithoutTrade(int.Parse(projectId), userLogged.ToString());
            locationViewModel.ProjectId = int.Parse(projectId);
            locationViewModel.projectImages = data;
            return Json(locationViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddMultipleImages()
        {
            var files = Request.Form.Files;
            var projectId = Request.Form["projectId"][0];


            foreach (var formFile in files)
            {
                ProjectTradeMaterialImage model = new ProjectTradeMaterialImage();
                if (formFile.Length > 0)
                {
                    using (var stream = new MemoryStream())
                    {
                        var user = await GetCurrentUserAsync();
                        await formFile.CopyToAsync(stream);
                        model.ProjectId = int.Parse(projectId);
                        model.LocationId = 0;
                        model.TradeId = 0;
                        model.MaterialId = 0;
                        model.Image = stream.ToArray();

SpecCoreOSDev/Core/src/SpecSheetsCore/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Repository;
using SpecSheetsCore.Models.LoggedInViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using SpecSheetsCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SpecSheetsCore.Controllers
{
	[Authorize]
	public class ReportsController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;

		public ReportsController(UserManager<ApplicationUser> userManager)
		{
			_userManager = userManager;
		}

		// GET: /<controller>/
		public async Task<IActionResult> Index()
		{
			// Generate the token and send it
			var user = await GetCurrentUserAsync();
			if (user == null)
			{
				return View("Error");
			}

			ReportsViewModel reports = new ReportsViewModel();

			reports.Projects = new List<SelectListItem>();
			reports.Projects.Add(new SelectListItem() { Text = "Select Project", Value = "0" });

			reports.Projects.AddRange(new ProjectRepository().GetProjectsByUserAccess(user.Id).Select(x => new SelectListItem() { Text = x.ProjectName, Value = x.ProjectId.ToString() }).ToList());

			return View(reports);
		}

		public JsonResult GetLocations(int ProjectId)
		{
			List<SelectListItem> ProjectLocations = new List<SelectListItem>();
			ProjectLocations.Add(new SelectListItem() { Text = "ALL", Value = "0" });
			ProjectLocations.AddRange(new LocationRepository().GetLocations(ProjectId).Select(x => new SelectListItem() { Text = x.LocationName, Value = x.LocationId.ToString() }).ToList());

			return Json(new SelectList(ProjectLocations, "Value", "Text"));
		}

		public JsonResult GetTrades(int ProjectId)
		{
			List<SelectListItem> ProjectLocations = new List<SelectListItem>();
			ProjectLocations.Add(new SelectListItem() { Text = "ALL", Value = "0" });
			ProjectLocations.AddRange(new TradeRepository().GetTradesByProjectId(ProjectId).Select(x => new SelectListItem() { Text = x.TradeName, Value = x.TradeId.ToString() }).ToList());

			return Json(new SelectList(ProjectLocations, "Value", "Text"));
		}

		public JsonResult GetUniqueTrades(int ProjectId)
		{
			List<SelectListItem> ProjectLocations = new List<SelectListItem>();
			ProjectLocations.Add(new SelectListItem() { Text = "ALL", Value = "0" });
			ProjectLocations.AddRange(new TradeRepository().GetUniqueTradesByProjectId(ProjectId).Select(trade => new SelectListItem() { Text = trade, Value = "1" }).ToList());

			return Json(new SelectList(ProjectLocations, "Value", "Text"));
		}

		public IActionResult ProjectDetails(int Id)
		{
			var projectDetails = new ProjectRepository().GetProjectDetailsWithTrades(Id);

			return new JsonResult(projectDetails);
		}

		public IActionResult ProjectDetailPage(int Id)
		{
			var projectDetails = new ProjectRepository().GetProjectDetailsWithTrades(Id);

			return new JsonResult(projectDetails);
		}

		public IActionResult LocationPageReport(int Id)
		{
			var locationDetails = new LocationRepository().GetLocation(Id, "");
			return new JsonResult(locationDetails);
		}

		public IActionResult LocationTradeReport(int Id, int TradeId)
		{
			var locationDetails = new LocationRepository().GetProjectLocationWithTrades(Id, TradeId);
			return new JsonResult(locationDetails);
		}

		public IActionResult LocationByProjectTrades(int Id, int TradeId) // Id = ProjectId, TradeId
		{
			var projectDetails = new ProjectRepository().GetProjectDetailsWithTrades(Id);
			return new JsonResult(projectDetails);
		}

		public IActionResult ReportTradesByLocation(int Id, int LocationId = 0)
		{
			var projectDetails = new ReportsRepository().ReportTradesByLocations(Id, LocationId);
			return new JsonResult(projectDetails);
		}

		//public IActionResult ReportLocationsByTrades(int Id, int TradeId = 0, string TradeName= "")
		//{
		//	var projectDetails = new ReportsRepository().ReportLocationsByTrades(Id, TradeId);
		//	return new JsonResult(projectDetails);
		//}

		public IActionResult ReportLocationsByTrades(int Id, string TradeName = "ALL")
		{
			int ProjectId = Id;
			var projectDetails = new ReportsRepository().ReportLocationsByTrades(ProjectId, TradeName);
			return new JsonResult(projectDetails);
		}

		private Task<ApplicationUser> GetCurrentUserAsync()
		{
			return _userManager.GetUserAsync(HttpContext.User);
		}
	}
}

SpecCoreOSDev/Core/src/SpecSheetsCore/Views/Shared/_LandingLayout.cshtml
@using Microsoft.AspNetCore.Identity
@using SpecSheetsCore.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpecSheetsCore</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="~/css/bootstrap.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,600,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">
									<img src="~/img/Logo.png" />"
								</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>

									@if (SignInManager.IsSignedIn(User))
									{
											<li><a asp-controller="Projects">Projects</a></li>
											<li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
									}


                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>

                </ul>
                @await Html.PartialAsync("_LandingLoginPartial")
            </div>
        </div>
    </div>
    <div class="">
        @RenderBody()
        <hr />
        <footer>
            <!-- begin:footer -->
            <div id="footer">
                <div class="container">
                   
                        <!-- break -->
                    </div>
                    <!-- break -->
                    <!-- begin:copyright -->
                    <div class="row">
                        <div class="col-md-12 copyright">
                            <p>Copyright &copy; @DateTime.Now.Year Spec Sheets, Inc. All Right Reserved.</p>
                            <p>Site : Designed by <strong>Source Systems Consulting, INC</strong></p>
                            <p>@ViewData["environment"]</p>
                            <a href="#top" class="btn btn-warning scroltop"><i class="fa fa-angle-up"></i></a>
                            <ul class="list-inline social-links">
                                <li><a  class="icon-twitter" rel="tooltip" title="" data-placement="bottom" data-original-title="Twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a  class="icon-facebook" rel="tooltip" title="" data-placement="bottom" data-original-title="Facebook"><i class="fa fa-facebook"></i></a></li>
                                <li><a  class="icon-gplus" rel="tooltip" title="" data-placement="bottom" data-original-title="Gplus"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- end:copyright -->

                </div>
            </div>
            <!-- end:footer -->
            <!-- begin:modal-signin -->
            <div class="modal fade" id="modal-signin" tabindex="-1" role="dialog" aria-labelledby="modal-signin" aria-hidden="true">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">Sign in</h4>
                        </div>
                        <div class="modal-body">
                            <form role="form">
                                <div class="form-group">
                                    <label for="emailAddress">Email address</label>
                                    <input type="email" class="form-control input-lg" placeholder="Enter email">
                                </div>
                                <div class="form-group">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control input-lg" placeholder="Password">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="forget"> Keep me logged in
                                    </label>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <p>Don't have account ? <a href="#modal-signup" data-toggle="modal" data-target="#modal-signup">Sign up here.</a></p>
                            <input type="submit" class="btn btn-warning btn-block btn-lg" value="Sign in">
                        </div>
                    </div>
                </div>
            </div>
            <!-- end:modal-signin -->
            <!-- begin:modal-signup -->
            <div class="modal fade" id="modal-signup" tabindex="-1" role="dialog" aria-labelledby="modal-signup" aria-hidden="true">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title">Sign up</h4>
                        </div>
                        <div class="modal-body">
                            <form role="form">
                                <div class="form-group">
                                    <input type="email" class="form-control input-lg" placeholder="Enter email">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control input-lg" placeholder="Password">
                                </div>
                                <div class="form-group">
                                    <input type="password" class="form-control input-lg" placeholder="Confirm Password">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="agree"> Agree to our <a href="#">terms of use</a> and <a href="#">privacy policy</a>
                                    </label>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <p>Already have account ? <a href="#modal-signin" data-toggle="modal" data-target="#modal-signin">Sign in here.</a></p>
                            <input type="submit" class="btn btn-warning btn-block btn-lg" value="Sign up">
                        </div>
                    </div>
                </div>
            </div>
            <!-- end:modal-signup -->
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

SpecCoreOSDev/Core/src/SpecSheetsCore/Views/Shared/_LandingLoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using SpecSheetsCore.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a asp-controller="Manage" asp-action="Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>
            </li>
            <li>
                <a title="Log off" href="#" onclick="document.getElementById('logoutForm').submit();">Log off</a>
            </li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-controller="Account" asp-action="Signup">Sign Up</a></li>
        <li><a asp-controller="Account" asp-action="Login">Log in</a></li>
    </ul>
}

SpecCoreOSDev/Core/src/SpecSheetsCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>SpecSheets - @ViewData["Title"]</title>

	<environment names="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link href='https://fonts.googleapis.com/css?family=Roboto:600,500,400,300' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
		<link rel="stylesheet" href="~/css/custom.css" type="text/css">
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment names="Staging,Production">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
					asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
					asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

		<link href='https://fonts.googleapis.com/css?family=Roboto:600,500,400,300' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
		<link rel="stylesheet" href="~/css/custom.css" type="text/css">
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>

</head>
<body>

	<div id="wrapper" class="clearfix">
		<header class="navbar-fixed-top">
			<div class="container-fluid">
				<a href="#menu-toggle" id="menu-toggle" class="slidePanel_btn">
					<span class="bar"></span>
					<span class="bar"></span>
					<span class="bar"></span>
				</a>
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
				<div class="right_btns nav-rbtns">
					<a href="/Reports"><i class="fa fa-print"></i></a>
					<a asp-area="" asp-controller="Account" asp-action="Information" title="Manage"><i class="fa fa-user fa-fw"></i> </a>
				</div>
			</div>
		</header>
		<div id="sidebar-wrapper">
			<ul>
				<li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home fa-fw"></i> Home</a></li>
				<li><a asp-area="" asp-controller="Projects" asp-action="Index"><i class="fa fa-file fa-fw"></i> Projects</a></li>
				<li><a asp-area="" asp-controller="Reports" asp-action="Index"><i class="fa fa-file fa-fw"></i> Print</a></li>
				<li><a asp-area="" asp-controller="Account" asp-action="Information"><i class="fa fa-user fa-fw"></i> Account Management</a></li>
				@*<li><a asp-area="Admin" asp-controller="Home" asp-action=""><i class="fa fa-user fa-fw"></i> Admin</a></li>*@
				@await Html.PartialAsync("_LoginPartial")
			</ul>
		</div>

		<section class="container">
			@RenderBody()
		</section>

	</div>
	<footer>©SpecSheets 2016 . All rights reserved.</footer>

	<environment names="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
		<script src="~/lib/Moment/moment.min.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>

		<script src="~/lib/jspdf/dist/jspdf.min.js"></script>
		<script src="~/lib/jspdf/plugins/jspdf.plugin.autotable.js"></script>
	</environment>
	<environment names="Staging,Production">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
						asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
						asp-fallback-test="window.jQuery">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
						asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
						asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
		</script>

		<script src="~/lib/jspdf/dist/jspdf.min.js"></script>
		<script src="~/lib/jspdf/plugins/jspdf.plugin.autotable.js"></script>
		<script src="~/lib/Moment/moment.min.js"></script>
		
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("scripts", required: false)

	<script>
		$("#menu-toggle").click(function (e) {
			e.preventDefault();
			$("#wrapper").toggleClass("toggled");
		});
	</script>

</body>
</html>